export const CREATE_EVENT_FAILED = "CREATE_EVENT_FAILED";
export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";

export const PARTICIPATE_EVENT_FAILED = "PARTICIPATE_EVENT_FAILED";
export const PARTICIPATE_EVENT_REQUEST = "PARTICIPATE_EVENT_REQUEST";
export const PARTICIPATE_EVENT_SUCCESS = "PARTICIPATE_EVENT_SUCCESS";


export const LEAVE_EVENT_FAILED = "LEAVE_EVENT_FAILED";
export const LEAVE_EVENT_REQUEST = "LEAVE_EVENT_REQUEST";
export const LEAVE_EVENT_SUCCESS = "LEAVE_EVENT_SUCCESS";

export const DELETE_EVENT_FAILED = "DELETE_EVENT_FAILED";
export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";

export const GET_ALL_EVENTS_REQUEST = "GET_ALL_EVENTS_REQUEST";
export const GET_ALL_EVENTS_FAILED = " GET_ALL_EVENTS_FAILED";
export const GET_ALL_EVENTS_SUCCESS = " GET_ALL_EVENTS_SUCCESS";
