export const GET_ALL_GROUPS_REQUEST = "GET_ALL_GROUPS_REQUEST";
export const GET_ALL_GROUPS_FAILED = "GET_ALL_GROUPS_FAILED";
export const GET_ALL_GROUPS_SUCCESS = "GET_ALL_GROUPS_SUCCESS";

export const CREATE_GROUP_REQUEST = "CREATE_GROUP_REQUESTT";
export const CREATE_GROUP_FAILED = "CREATE_GROUP_FAILED";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";

export const DELETE_GROUP_REQUEST = "DELETE_GROUP_REQUESTT";
export const DELETE_GROUP_FAILED = "DELETE_GROUP_FAILED";
export const DELETE_GROUP_SUCCESS = "DELETE_GROUP_SUCCESS";

export const JOIN_GROUP_REQUEST = "JOIN_GROUP_REQUEST";
export const JOIN_GROUP_SUCCESS = "JOIN_GROUP_SUCCESS";
export const JOIN_GROUP_FAILED = "JOIN_GROUP_FAILED";

export const LEAVE_GROUP_REQUEST = "LEAVE_GROUP_REQUEST";
export const LEAVE_GROUP_SUCCESS = "LEAVE_GROUP_SUCCESS";
export const LEAVE_GROUP_FAILED = "LEAVE_GROUP_FAILED";

export const GET_ALL_MEMBERS_GROUP_REQUEST = "GET_ALL_MEMBERS_GROUP_REQUEST";
export const GET_ALL_MEMBERS_GROUP_SUCCESS = "GET_ALL_MEMBERS_GROUP_SUCCESS";
export const GET_ALL_MEMBERS_GROUP_FAILED = "GET_ALL_MEMBERS_GROUP_FAILED";



export const DELETE_MEMBER_GROUP_REQUEST = "DELETE_MEMBER_GROUP_REQUEST";
export const DELETE_MEMBER_GROUP_SUCCESS = "DELETE_MEMBER_GROUP_SUCCESS";
export const DELETE_MEMBER_GROUP_FAILED = "DELETE_MEMBER_GROUP_FAILED";

export const SEND_MESSAGE_GROUP_REQUEST = "SEND_MESSAGE_GROUP_REQUEST";
export const SEND_MESSAGE_GROUP_SUCCESS = "SEND_MESSAGE_GROUP_SUCCESS";
export const SEND_MESSAGE_GROUP_FAILED = "SEND_MESSAGE_GROUP_FAILED";


export const GET_MESSAGE_GROUP_REQUEST = "GET_MESSAGE_GROUP_REQUEST";
export const GET_MESSAGE_GROUP_SUCCESS = "GET_MESSAGE_GROUP_SUCCESS";
export const GET_MESSAGE_GROUP_FAILED = "GET_MESSAGE_GROUP_FAILED";