export const GET_ARTICLES_REQUEST = "GET_ARTICLES_REQUEST"
export const GET_ARTICLES_FAILED = "GET_ARTICLES_FAILED";
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";

export const CREATE_ARTICLES_REQUEST = "CREATE_ARTICLES_REQUEST";
export const CREATE_ARTICLES_FAILED = "CREATE_ARTICLES_FAILED";
export const CREATE_ARTICLES_SUCCESS = "CREATE_ARTICLES_SUCCESS";
