export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST";
export const GET_ALL_POSTS_FAILED = "GET_ALL_POSTS_FAILED";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_FAILED = "CREATE_POST_FAILED";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_FAILED = "DELETE_POST_FAILED";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";


export const GET_POST_BY_USER_REQUEST = "GET_POST_BY_USER_REQUEST";
export const GET_POST_BY_USER_SUCCESS = "GET_POST_BY_USER_SUCCESS";
export const GET_POST_BY_USER_FAILED = "GET_POST_BY_USER_FAILED";


export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_FAILED = "LIKE_POST_FAILED";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";

export const UNLIKE_POST_REQUEST = "UNLIKE_POST_REQUEST";
export const UNLIKE_POST_FAILED = "UNLIKE_POST_FAILED";
export const UNLIKE_POST_SUCCESS = "UNLIKE_POST_SUCCESS";

export const GET_ALL_LIKES_REQUEST = "GET_ALL_LIKES_REQUEST";
export const GET_ALL_LIKES_FAILED =  "GET_ALL_LIKES_FAILED";
export const GET_ALL_LIKES_SUCCESS = "GET_ALL_LIKES_SUCCESS";


export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST";
export const POST_COMMENT_FAILED =  "POST_COMMENT_FAILED";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";

export const GET_ALL_COMMENT_REQUEST = "GET_ALL_COMMENT_REQUEST";
export const GET_ALL_COMMENT_FAILED =  "GET_ALL_COMMENT_FAILED";
export const GET_ALL_COMMENT_SUCCESS = "GET_ALL_COMMENT_SUCCESS";
