export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR'


export const GET_USER = 'GET_USER';
export const USER_ERROR = 'USER_ERROR'


export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR   = 'UPDATE_USER_ERROR'